spring:
  datasource:
    url: jdbc:mysql://121.153.139.131/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: gksryaA1!2
    driver-class-name: com.mysql.cj.jdbc.Driver